services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: autoshop
      POSTGRES_PASSWORD: autoshop123
      POSTGRES_DB: autoshop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: 192.168.100.64:8082/autoshop-backend:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8000"

  frontend:
    image: 192.168.100.64:8082/autoshop-frontend:latest
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:

